const worldDishes: Record<string, string> = {
  "af": "Kabuli Pulao",
  "al": "Tavë Kosi",
  "dz": "Couscous",
  "ad": "Trinxat",
  "ao": "Funje And Muamba",
  "ag": "Pepperpot",
  "ar": "Asado",
  "am": "Khorovats",
  "au": "Meat Pie",
  "at": "Wiener Schnitzel",
  "az": "Plov",
  "bs": "Conch Fritters",
  "bh": "Machboos",
  "bd": "Biryani",
  "bb": "Flying Fish And Cou-Cou",
  "by": "Draniki",
  "be": "Moules-Frites",
  "bz": "Rice And Beans",
  "bj": "Amiwo",
  "bt": "Ema Datshi",
  "bo": "Salteñas",
  "ba": "Ćevapi",
  "bw": "Seswaa",
  "br": "Feijoada",
  "bn": "Ambuyat",
  "bg": "Banitsa",
  "bf": "Riz Gras",
  "bi": "Brochettes",
  "kh": "Amok",
  "cm": "Ndolé",
  "ca": "Poutine",
  "cv": "Cachupa",
  "cf": "Cassava And Peanut Stew",
  "td": "Daraba (Peanut-Vegetable Stew)",
  "cl": "Pastel De Choclo",
  "cn": "Peking Duck",
  "co": "Bandeja Paisa",
  "km": "Langouste À La Vanille",
  "cg": "Poulet Nyembwe",
  "cr": "Gallo Pinto",
  "hr": "Peka",
  "cu": "Ropa Vieja",
  "cy": "Souvlaki",
  "cz": "Svíčková",
  "dk": "Smørrebrød",
  "dj": "Skoudehkaris",
  "dm": "Callaloo",
  "do": "La Bandera",
  "ec": "Ceviche",
  "eg": "Koshary",
  "sv": "Pupusas",
  "gq": "Groundnut Stew",
  "er": "Zigni",
  "ee": "Mulgipuder",
  "et": "Doro Wat With Injera",
  "fj": "Kokoda",
  "fi": "Karjalanpiirakka",
  "fr": "Coq Au Vin",
  "ga": "Poulet Nyembwe",
  "gm": "Domoda",
  "ge": "Khachapuri",
  "de": "Sauerbraten",
  "gh": "Jollof Rice",
  "gr": "Moussaka",
  "gd": "Oil Down",
  "gt": "Pepian",
  "gn": "Poulet Yassa",
  "gw": "Caldo De Peixe",
  "gy": "Pepperpot",
  "ht": "Griot",
  "hn": "Baleadas",
  "hu": "Goulash",
  "is": "Hákarl",
  "in": "Biryani",
  "id": "Nasi Goreng",
  "ir": "Chelo Kebab",
  "iq": "Masgouf",
  "ie": "Irish Stew",
  "il": "Hummus",
  "it": "Pizza Napoletana",
  "ci": "Attiéké With Grilled Fish",
  "jm": "Ackee And Saltfish",
  "jp": "Sushi",
  "jo": "Mansaf",
  "kz": "Beshbarmak",
  "ke": "Nyama Choma",
  "ki": "Fish With Coconut",
  "kp": "Naengmyeon",
  "kr": "Bibimbap",
  "xk": "Flia",
  "kw": "Machboos",
  "kg": "Beshbarmak",
  "la": "Larb (Laap)",
  "lv": "Grey Peas And Bacon",
  "lb": "Kibbeh",
  "ls": "Pap And Stew",
  "lr": "Jollof Rice",
  "ly": "Couscous",
  "li": "Käsknöpfle",
  "lt": "Cepelinai",
  "lu": "Judd Mat Gaardebounen",
  "mk": "Tavče Gravče",
  "mg": "Romazava",
  "mw": "Nsima With Chambo",
  "my": "Nasi Lemak",
  "mv": "Mas Huni",
  "ml": "Tô",
  "mt": "Fenkata (Rabbit Stew)",
  "mh": "Fish With Coconut",
  "mr": "Thieboudienne",
  "mu": "Dholl Puri",
  "mx": "Tacos Al Pastor",
  "fm": "Grilled Fish With Taro",
  "md": "Mămăligă With Sarmale",
  "mc": "Barbagiuan",
  "mn": "Buuz",
  "me": "Ćevapi",
  "ma": "Tagine",
  "mz": "Matapa",
  "mm": "Mohinga",
  "na": "Kapana",
  "nr": "Coconut Fish",
  "np": "Dal Bhat",
  "nl": "Stamppot",
  "nz": "Hangi",
  "ni": "Gallo Pinto",
  "ne": "Jollof Rice",
  "ng": "Jollof Rice",
  "no": "Fårikål",
  "om": "Shuwa",
  "pk": "Biryani",
  "pw": "Taro And Fish",
  "pa": "Sancocho",
  "pg": "Mumu",
  "py": "Sopa Paraguaya",
  "pe": "Ceviche",
  "ph": "Adobo",
  "pl": "Pierogi",
  "pt": "Bacalhau",
  "qa": "Machboos",
  "ro": "Sarmale",
  "ru": "Borscht",
  "rw": "Isombe",
  "kn": "Stewed Saltfish",
  "lc": "Green Fig And Saltfish",
  "vc": "Roasted Breadfruit And Jackfish",
  "ws": "Oka (Raw Fish In Coconut)",
  "sm": "Torta Tre Monti",
  "st": "Calulu",
  "sa": "Kabsa",
  "sn": "Thieboudienne",
  "rs": "Ćevapi",
  "sc": "Octopus Curry",
  "sl": "Cassava Leaves With Fish",
  "sg": "Hainanese Chicken Rice",
  "sk": "Bryndzové Halušky",
  "si": "Potica",
  "sb": "Poi",
  "so": "Bariis Iskukaris",
  "za": "Bobotie",
  "ss": "Kisra And Nyama",
  "es": "Paella",
  "lk": "Rice And Curry",
  "sd": "Ful Medames",
  "sr": "Pom",
  "sz": "Sishwala",
  "se": "Swedish Meatballs",
  "ch": "Fondue",
  "sy": "Kibbeh",
  "tj": "Qurutob",
  "tz": "Ugali With Nyama Choma",
  "th": "Pad Thai",
  "tl": "Ikan Pepes",
  "tg": "Fufu And Stew",
  "to": "Lu Pulu",
  "tt": "Bake And Shark",
  "tn": "Couscous",
  "tr": "Kebab",
  "tm": "Plov",
  "ug": "Matoke",
  "ua": "Borscht",
  "ae": "Al Machboos",
  "gb": "Fish And Chips",
  "us": "Hamburger",
  "uy": "Asado",
  "uz": "Plov",
  "vu": "Laplap",
  "va": "Pasta",
  "ve": "Arepa",
  "vn": "Pho",
  "ye": "Saltah",
  "zm": "Nshima",
  "zw": "Sadza"
}

export default worldDishes;